{
 "title": "JMeter Farm Injector JSR223",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Transaction",
    "query": "SHOW TAG VALUES FROM \"samples\" WITH KEY = \"label\" WHERE \"type\"='TRANSACTION'"
   },
   {
    "name": "Request",
    "query": "SHOW TAG VALUES FROM \"samples\" WITH KEY = \"label\" WHERE \"type\"='REQUEST'"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of concurrent users (by injector)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nombre requêtes per 10 secondes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Req / 10 sec",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response time of all transactions (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_label",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "Failure" }
     ]
    }
   ]
  },
  {
   "title": "Transactions with highest response time (ms)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "$tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "Failure" },
      { "condition": "AND", "key": "responsecode", "operator": "=", "value": "-1" }
     ]
    }
   ]
  },
  {
   "title": "Error's most frequent response code",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "$tag_responsecode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "responsecode" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "samples",
     "query": "SELECT sum(\"count\") FROM \"samples\" WHERE (\"type\" = 'REQUEST') AND $timeFilter GROUP BY time($__interval), \"responsecode\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "REQUEST" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "Failure" }
     ]
    }
   ]
  },
  {
   "title": "Error per Transaction",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "alias": "$tag_transactioname",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transactioname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "Failure" },
      { "condition": "AND", "key": "responsecode", "operator": "!=", "value": "-1" }
     ]
    }
   ]
  },
  {
   "title": "Transaction : $Transaction",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "content": "\n\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Transaction : Response time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$Transaction",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=~", "value": "/^$Transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "$Transaction : Total errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "samples",
     "query": "SELECT sum(\"count\") FROM \"samples\" WHERE (\"label\" =~ /^$Transaction$/) AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "transactioname", "operator": "=~", "value": "/^$Transaction$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "Failure" }
     ]
    }
   ]
  },
  {
   "title": "Request : $Request",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Transaction - $Request : Response time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "samples",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=~", "value": "/^$Request$/" }
     ]
    }
   ]
  },
  {
   "title": "$Transaction - $Request : Total errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "samples",
     "query": "SELECT sum(\"count\") FROM \"samples\" WHERE (\"label\" =~ /^$Transaction$/) AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "transactioname", "operator": "=~", "value": "/^$Transaction$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "Failure" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$Request$/" }
     ]
    }
   ]
  }
 ]
}