apiVersion: batch/v1
kind: Job
metadata:
  name: jmeterkey
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: jmeterkey
    spec:
      containers:
        - name: jmeterkey
          image: docker-registry-default.app.leanovia.net/project/jmeterkey:latest
      restartPolicy: OnFailure