apiVersion: batch/v1
kind: Job
metadata:
  name: jobjmetermain
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: jmetermain
    spec:
      containers:
        - name: jmetermain
          image: docker-registry.default.svc:5000/jmeter/jmetermain
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: password
                  name: jmeter-token
      restartPolicy: Never