apiVersion: batch/v1
kind: Job
metadata:
  name: jobjmeterkey
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: jmeterkey
    spec:
      containers:
        - name: jmeterkey
          image: docker-registry.default.svc:5000/jmeter/jmeterkey
          volumeMounts:
            - mountPath: /SharedVolume
              name: pvjmeter
      restartPolicy: Never
      volumes:
        - name: pvjmeter
          persistentVolumeClaim:
            claimName: jmeter