---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobjmeterserv
spec:
  parallelism: 2
  completions: 2
  template:
    metadata:
      name: jmeterserv
    spec:
      containers:
      - name: jmeterserv
        image: docker-registry.default.svc:5000/jmeter/jmeterserv
        volumeMounts:
        - mountPath: "/SharedVolume"
          name: pvjmeter
        readinessProbe:
          exec:
            command:
            - "/scriptReturnReadiness.sh"
            - "$READY"
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Never
      volumes:
      - name: pvjmeter
        persistentVolumeClaim:
          claimName: jmeter

