---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobjmetercont
  namespace: jmeter
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: jmetercont
    spec:
      containers:
      - name: jmetercont
        image: docker-registry.default.svc:5000/jmeter/jmetercont
        volumeMounts:
        - mountPath: "/SharedVolume"
          name: pvjmeter
      restartPolicy: Never
      volumes:
      - name: pvjmeter
        persistentVolumeClaim:
          claimName: jmeter

