apiVersion: batch/v1
kind: Job
metadata:
  name: jobjmeterserv
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: jmeterserv
    spec:
      activeDeadlineSeconds: 180
      containers:
        - name: jmeterserv
          image: docker-registry.default.svc:5000/jmeter/jmetercont
          volumeMounts:
            - mountPath: /SharedVolume
              name: pvjmeter
      restartPolicy: Never
      volumes:
        - name: pvjmeter
          persistentVolumeClaim:
            claimName: jmeter